### ISSUE TITLE
different data formats on dataverse

### ISSUE THREAD

**Issue by resulumit** [hdigital/partyfactsdata#53]
On Harvard Dataverse, where the stable versions of the Party Facts datasets are available, most data files have the .tab extension. There are three exceptions:

1. https://dataverse.harvard.edu/file.xhtml?fileId=4274155&version=1.1
2. https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/UUMC31/JEM0W5&version=1.0
3. https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/FTQAYT/L8EGUM&version=1.0

These have the .csv extension. 

If this is not on purpose, perhaps all files could be of the same format for consistency reasons. I realised this difference when I was trying to write a function that would get these files systematically, where the extension makes a difference.

Perhaps this is not possible and/or desirable. In any case, let me say thank you for this great resource.

**Comment by pbederke** [comment]
Thank you for your comment and first of all sorry for the late reply. It is the first time someone opened an issue on our public GitHub repository. It looks like that there has been some error during the upload on the Harvard Dataverse. I re-uploaded the files and this error should now be fixed.

1. [https://dataverse.harvard.edu/file.xhtml?fileId=5658918&version=2.0](https://dataverse.harvard.edu/file.xhtml?fileId=5658918&version=2.0)
2. [https://dataverse.harvard.edu/file.xhtml?fileId=5658910&version=2.0](https://dataverse.harvard.edu/file.xhtml?fileId=5658910&version=2.0)
3. [https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FTQAYT](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FTQAYT)

Again, thank you for pointing this out!
