### ISSUE TITLE
partyfacts-clea.csv appears to be incomplete/outdated

### ISSUE THREAD

**Issue by cosmojg** [hdigital/partyfactsdata#58]
The file at https://github.com/hdigital/partyfactsdata/blob/master/import/clea/partyfacts-clea.csv appears to be missing some parties.

For example, Demokratikus Koalíció with partyfacts_id = 469 (see: https://partyfacts.herokuapp.com/data/partycodes/469/) and dataset_party_id = 348000004 (see: https://partyfacts.herokuapp.com/data/partyall/51923/) does not appear in the file.

Interestingly, Demokratikus Koalíció is listed in clea.csv at https://github.com/hdigital/partyfactsdata/blob/master/import/clea/clea.csv with party_id = 348000004.

Where should I look if I want a more complete/up-to-date version of partyfacts-clea.csv?

Alternatively, if such a file does not already exist or cannot be provided, do you know how I can generate a complete version of partyfacts-clea.csv on my own using the data available online at https://partyfacts.herokuapp.com/ ?

**Comment by pbederke** [comment]
Thanks for pointing out this issue, the file was outdated! I have updated the file which you can find at [https://github.com/hdigital/partyfactsdata/blob/master/import/clea/partyfacts-clea.csv](https://github.com/hdigital/partyfactsdata/blob/master/import/clea/partyfacts-clea.csv).

Alternatively, you can always get the latest data online at [https://partyfacts.herokuapp.com/download/](https://partyfacts.herokuapp.com/download/). The file for _external parties_ includes the Party ID (`dataset_party_id`) as it is in the external dataset and the Party Facts ID (`partyfacts_id`). You need to filter `dataset_key` to get only the ones for CLEA.

**Comment by cosmojg** [comment]
Thanks a million, @pbederke!
