### ISSUE TITLE
harvard elections data is often wrong

### ISSUE THREAD

**Issue by rcyost** [hdigital/partyfactsdata#71]
<img width="996" alt="image" src="https://github.com/hdigital/partyfactsdata/assets/32645001/5c2d566f-f57b-4613-b83d-cddd464dce8e">
Vicente Fox won the 2000 election in Mexico, he is in the PAN party. But the elections global release data has the PRI winning 2000 with 35.1% of votes vs PAN's 34.6% of votes. 
<img width="649" alt="image" src="https://github.com/hdigital/partyfactsdata/assets/32645001/40ed80e2-fca6-4be9-a3a6-fe36c0b24a49">

In fact, if you merge their global leaders dataset with the elections dataset, very often does the President of a country in a year not line up with who they say won the election in a country, year pair. Unless someone can point out to me what is going on, this is seriously poor quality data and needs to be removed less people use it.

**Comment by pbederke** [comment]
@rcyost The _Elections Global_ dataset only includes the results of elections to the 1st or "lower" chambers. The codebook explicitly states that presidential elections are not included. Therefore, there may be differences between the winning party in the _Elections Global_ dataset and the party affiliation of the president in the _Leaders Global_ dataset. Hope this could give some clarification.

**Comment by rcyost** [comment]
Gotcha, thank you. Taking a look at the codebook now. What am I missing? Why have a leaders dataset of presidents and the elections dataset be for the lower chamber? They are incomparable, no? Wouldn't it make sense to do all that work to match the leaders to the elections? Thanks.

**Comment by pbederke** [comment]
The _Leaders Global_ dataset contains the Head of Government (HoG) and Head of State (HoS) for countries around the world through time, it is not limited to presidential systems. Hence, for some countries the president is reported and in others the prime minister (or equivalent). 

The _Leaders Global_ and _Elections Global_ have been two separate projects that had different objectives. Therefore, _Elections Global_ focuses on elections of the lower chamber and _Leaders Global_ on the party affiliation of the HoG and HoS. For data on presidential election results, you need to find an alternative.

On a side note: While we as individual scholars were involved in the compilation of these two datasets, Party Facts as database is a separate project and only provides information on linking party information across different dataset. Party Facts does not create new party information but links different projects with each other. Therefore, the Party Facts project is in general not responsible for the coding decisions of the included datasets.
